import { genConfig, AvatarFullConfig } from 'react-nice-avatar';

const avatar1 = {
  sex: 'man',
  faceColor: '#F9C9B6',
  earSize: 'big',
  eyeStyle: 'smile',
  noseStyle: 'long',
  mouthStyle: 'smile',
  shirtStyle: 'hoody',
  glassesStyle: 'none',
  hairColor: '#000',
  hairStyle: 'mohawk',
  hatStyle: 'none',
  hatColor: '#F48150',
  eyeBrowStyle: 'up',
  shirtColor: '#6BD9E9',
  bgColor: 'linear-gradient(45deg, #3e1ccd 0%, #ff6871 100%)',
};

const avatar2 = {
  sex: 'man',
  faceColor: '#F9C9B6',
  earSize: 'small',
  eyeStyle: 'circle',
  noseStyle: 'round',
  mouthStyle: 'laugh',
  shirtStyle: 'hoody',
  glassesStyle: 'none',
  hairColor: '#506AF4',
  hairStyle: 'normal',
  hatStyle: 'none',
  hatColor: '#000',
  eyeBrowStyle: 'up',
  shirtColor: '#FC909F',
  bgColor: '#F4D150',
};

const avatar3 = {
  sex: 'woman',
  faceColor: '#AC6651',
  earSize: 'small',
  eyeStyle: 'circle',
  noseStyle: 'short',
  mouthStyle: 'laugh',
  shirtStyle: 'short',
  glassesStyle: 'none',
  hairColor: '#506AF4',
  hairStyle: 'normal',
  hatStyle: 'turban',
  hatColor: '#F48150',
  eyeBrowStyle: 'upWoman',
  shirtColor: '#77311D',
  bgColor: 'linear-gradient(45deg, #176fff 0%, #68ffef 100%)',
};

const avatar4 = {
  sex: 'woman',
  faceColor: '#F9C9B6',
  earSize: 'small',
  eyeStyle: 'smile',
  noseStyle: 'short',
  mouthStyle: 'smile',
  shirtStyle: 'polo',
  glassesStyle: 'none',
  hairColor: '#FC909F',
  hairStyle: 'womanShort',
  hatStyle: 'none',
  hatColor: '#F48150',
  eyeBrowStyle: 'upWoman',
  shirtColor: '#6BD9E9',
  bgColor: 'linear-gradient(45deg, #1729ff 0%, #ff56f7 100%)',
};

const avatar5 = {
  sex: 'woman',
  faceColor: '#F9C9B6',
  earSize: 'big',
  eyeStyle: 'oval',
  noseStyle: 'round',
  mouthStyle: 'peace',
  shirtStyle: 'short',
  glassesStyle: 'none',
  hairColor: '#fff',
  hairStyle: 'womanLong',
  hatStyle: 'none',
  hatColor: '#506AF4',
  eyeBrowStyle: 'upWoman',
  shirtColor: '#77311D',
  bgColor: '#E0DDFF',
};

const avatar6 = {
  sex: 'man',
  faceColor: '#F9C9B6',
  earSize: 'small',
  eyeStyle: 'oval',
  noseStyle: 'short',
  mouthStyle: 'peace',
  shirtStyle: 'hoody',
  glassesStyle: 'none',
  hairColor: '#000',
  hairStyle: 'normal',
  hatStyle: 'none',
  hatColor: '#fff',
  eyeBrowStyle: 'up',
  shirtColor: '#F4D150',
  bgColor: '#506AF4',
};

const avatar7 = {
  sex: 'man',
  faceColor: '#F9C9B6',
  earSize: 'small',
  eyeStyle: 'smile',
  noseStyle: 'short',
  mouthStyle: 'peace',
  shirtStyle: 'hoody',
  glassesStyle: 'none',
  hairColor: '#fff',
  hairStyle: 'normal',
  hatStyle: 'none',
  hatColor: '#506AF4',
  eyeBrowStyle: 'up',
  shirtColor: '#9287FF',
  bgColor: 'linear-gradient(45deg, #ff1717 0%, #ffd368 100%)',
};

const avatar8 = {
  sex: 'woman',
  faceColor: '#AC6651',
  earSize: 'small',
  eyeStyle: 'smile',
  noseStyle: 'round',
  mouthStyle: 'peace',
  shirtStyle: 'hoody',
  glassesStyle: 'none',
  hairColor: '#F48150',
  hairStyle: 'normal',
  hatStyle: 'none',
  hatColor: '#F48150',
  eyeBrowStyle: 'upWoman',
  shirtColor: '#FC909F',
  bgColor: '#FFEBA4',
};

const avatar9 = {
  sex: 'woman',
  faceColor: '#F9C9B6',
  earSize: 'big',
  eyeStyle: 'oval',
  noseStyle: 'round',
  mouthStyle: 'laugh',
  shirtStyle: 'short',
  glassesStyle: 'none',
  hairColor: '#77311D',
  hairStyle: 'womanShort',
  hatStyle: 'none',
  hatColor: '#506AF4',
  eyeBrowStyle: 'upWoman',
  shirtColor: '#FC909F',
  bgColor: 'linear-gradient(45deg, #56b5f0 0%, #45ccb5 100%)',
};

const avatar10 = {
  sex: 'man',
  faceColor: '#F9C9B6',
  earSize: 'big',
  eyeStyle: 'circle',
  noseStyle: 'long',
  mouthStyle: 'peace',
  shirtStyle: 'polo',
  glassesStyle: 'none',
  hairColor: '#000',
  hairStyle: 'thick',
  hatStyle: 'none',
  hatColor: '#77311D',
  eyeBrowStyle: 'up',
  shirtColor: '#F4D150',
  bgColor: '#FC909F',
};

const avatar11 = {
  sex: 'woman',
  faceColor: '#AC6651',
  earSize: 'small',
  eyeStyle: 'smile',
  noseStyle: 'long',
  mouthStyle: 'peace',
  shirtStyle: 'polo',
  glassesStyle: 'none',
  hairColor: '#fff',
  hairStyle: 'womanShort',
  hatStyle: 'none',
  hatColor: '#506AF4',
  eyeBrowStyle: 'up',
  shirtColor: '#FC909F',
  bgColor: '#6BD9E9',
};

const avatar12 = {
  sex: 'man',
  faceColor: '#AC6651',
  earSize: 'small',
  eyeStyle: 'smile',
  noseStyle: 'short',
  mouthStyle: 'laugh',
  shirtStyle: 'hoody',
  glassesStyle: 'none',
  hairColor: '#000',
  hairStyle: 'thick',
  hatStyle: 'none',
  hatColor: '#F48150',
  eyeBrowStyle: 'up',
  shirtColor: '#FC909F',
  bgColor: '#FFEDEF',
};

const avatar13 = {
  sex: 'woman',
  faceColor: '#AC6651',
  earSize: 'small',
  eyeStyle: 'oval',
  noseStyle: 'long',
  mouthStyle: 'peace',
  shirtStyle: 'polo',
  glassesStyle: 'none',
  hairColor: '#000',
  hairStyle: 'womanLong',
  hatStyle: 'none',
  hatColor: '#506AF4',
  eyeBrowStyle: 'up',
  shirtColor: '#9287FF',
  bgColor: 'linear-gradient(45deg, #178bff 0%, #ff6868 100%)',
};

const avatar14 = {
  sex: 'woman',
  faceColor: '#F9C9B6',
  earSize: 'small',
  eyeStyle: 'smile',
  noseStyle: 'short',
  mouthStyle: 'laugh',
  shirtStyle: 'short',
  glassesStyle: 'none',
  hairColor: '#77311D',
  hairStyle: 'normal',
  hatStyle: 'none',
  hatColor: '#FC909F',
  eyeBrowStyle: 'up',
  shirtColor: '#F4D150',
  bgColor: 'linear-gradient(45deg, #ff1717 0%, #ffd368 100%)',
};

const avatar15 = {
  sex: 'man',
  faceColor: '#AC6651',
  earSize: 'small',
  eyeStyle: 'circle',
  noseStyle: 'short',
  mouthStyle: 'peace',
  shirtStyle: 'short',
  glassesStyle: 'none',
  hairColor: '#D2EFF3',
  hairStyle: 'thick',
  hatStyle: 'none',
  hatColor: '#F48150',
  eyeBrowStyle: 'up',
  shirtColor: '#6BD9E9',
  bgColor: 'linear-gradient(45deg, #56b5f0 0%, #45ccb5 100%)',
};

const avatar16 = {
  sex: 'man',
  faceColor: '#F9C9B6',
  earSize: 'small',
  eyeStyle: 'circle',
  noseStyle: 'short',
  mouthStyle: 'laugh',
  shirtStyle: 'short',
  glassesStyle: 'none',
  hairColor: '#D2EFF3',
  hairStyle: 'thick',
  hatStyle: 'none',
  hatColor: '#D2EFF3',
  eyeBrowStyle: 'up',
  shirtColor: '#77311D',
  bgColor: 'linear-gradient(45deg, #178bff 0%, #ff6868 100%)',
};

const avatar17 = {
  sex: 'woman',
  faceColor: '#F9C9B6',
  earSize: 'small',
  eyeStyle: 'circle',
  noseStyle: 'long',
  mouthStyle: 'peace',
  shirtStyle: 'short',
  glassesStyle: 'none',
  hairColor: '#fff',
  hairStyle: 'thick',
  hatStyle: 'beanie',
  hatColor: '#D2EFF3',
  eyeBrowStyle: 'up',
  shirtColor: '#6BD9E9',
  bgColor: '#9287FF',
  isGradient: false,
  hairColorRandom: false,
};

export const avatarName = [
  'avatar1',
  'avatar2',
  'avatar3',
  'avatar4',
  'avatar5',
  'avatar6',
  'avatar7',
  'avatar8',
  'avatar9',
  'avatar10',
  'avatar11',
  'avatar12',
  'avatar13',
  'avatar14',
  'avatar15',
  'avatar16',
  'avatar17',
];

export const avatars = new Map([
  ['avatar1', genConfig(avatar1 as AvatarFullConfig)],
  ['avatar2', genConfig(avatar2 as AvatarFullConfig)],
  ['avatar3', genConfig(avatar3 as AvatarFullConfig)],
  ['avatar4', genConfig(avatar4 as AvatarFullConfig)],
  ['avatar5', genConfig(avatar5 as AvatarFullConfig)],
  ['avatar6', genConfig(avatar6 as AvatarFullConfig)],
  ['avatar7', genConfig(avatar7 as AvatarFullConfig)],
  ['avatar8', genConfig(avatar8 as AvatarFullConfig)],
  ['avatar9', genConfig(avatar9 as AvatarFullConfig)],
  ['avatar10', genConfig(avatar10 as AvatarFullConfig)],
  ['avatar11', genConfig(avatar11 as AvatarFullConfig)],
  ['avatar12', genConfig(avatar12 as AvatarFullConfig)],
  ['avatar13', genConfig(avatar13 as AvatarFullConfig)],
  ['avatar14', genConfig(avatar14 as AvatarFullConfig)],
  ['avatar15', genConfig(avatar15 as AvatarFullConfig)],
  ['avatar16', genConfig(avatar16 as AvatarFullConfig)],
  ['avatar17', genConfig(avatar17 as AvatarFullConfig)],
]);
